- name: 'Build Jenkins AMI'
  hosts: localhost
  tasks:
  - include_role:
     name: alpha-deploy-lib/deploy-cloudformation
    vars:
      type: 'BASE'
      cloud_formation: '{{ playbook_dir }}/files/base.yml'

  - set_fact:
      params: '{{ params | combine( cloud_formation_output["stack_outputs"] ) }}'

  - template:
      src: '{{ playbook_dir }}/templates/mgmt.yml'
      dest: '{{ playbook_dir }}/files/mgmt.yml'

  - include_role:
      name: alpha-deploy-lib/deploy-cloudformation
    vars:
      type: 'MGMT'
      cloud_formation: '{{ playbook_dir }}/files/mgmt.yml'

  - include_role:
      name: alpha-deploy-lib/deploy-cloudformation
    vars:
      type: 'BOT'
      cloud_formation: '{{ playbook_dir }}/files/jira.yml'


  - include_role:
      name: alpha-deploy-lib/cognito-idp-add-user
    vars:
      username: 'admin'
      cognito_groups:
      - administrators

