AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentNameLower:
    Type: String
  EnvironmentNameUpper:
    Type: String
  PublicHostedZoneName:
    Type: String
  PublicHostedZoneId:
    Type: String

Resources:
  GlobalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${PublicHostedZoneName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "*.${PublicHostedZoneName}"
          HostedZoneId: !Sub "${PublicHostedZoneId}"

Outputs:
  GlobalCertificateArn:
    Value: !Ref GlobalCertificate